# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('grade', models.SmallIntegerField(choices=[(0, '0stars'), (1, '1stars'), (2, '2stars'), (3, '3stars'), (4, '4stars'), (5, '5stars')], verbose_name='grade')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='grader')),
            ],
            options={
                'verbose_name': 'star',
                'verbose_name_plural': 'stars',
            },
        ),
    ]
