# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 02:04
from __future__ import unicode_literals

import applications.playList.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is_private'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, upload_to=applications.playList.models.song_name, verbose_name='song_file'),
        ),
    ]
