# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
        ('playList', '0002_auto_20160511_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='playlist_song_stars', to='ranking.Stars', verbose_name='stars'),
        ),
    ]
