# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playList', '0003_song_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='star_ranking',
            field=models.FloatField(default=0, verbose_name='star_ranking'),
        ),
    ]
